package com.cx.codesigner.dao;

import com.cx.codesigner.model.SearchType;
import com.cx.codesigner.model.SearchTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SearchTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchtype
     *
     * @mbggenerated
     */
    int countByExample(SearchTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchtype
     *
     * @mbggenerated
     */
    int deleteByExample(SearchTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchtype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchtype
     *
     * @mbggenerated
     */
    int insert(SearchType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchtype
     *
     * @mbggenerated
     */
    int insertSelective(SearchType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchtype
     *
     * @mbggenerated
     */
    List<SearchType> selectByExample(SearchTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchtype
     *
     * @mbggenerated
     */
    SearchType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchtype
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SearchType record, @Param("example") SearchTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchtype
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SearchType record, @Param("example") SearchTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchtype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SearchType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchtype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SearchType record);
}