package com.cx.codesigner.model;

import java.util.ArrayList;
import java.util.List;

public class MyUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table myuser
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table myuser
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table myuser
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbggenerated
     */
    public MyUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table myuser
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andRealnameIsNull() {
            addCriterion("realname is null");
            return (Criteria) this;
        }

        public Criteria andRealnameIsNotNull() {
            addCriterion("realname is not null");
            return (Criteria) this;
        }

        public Criteria andRealnameEqualTo(String value) {
            addCriterion("realname =", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotEqualTo(String value) {
            addCriterion("realname <>", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameGreaterThan(String value) {
            addCriterion("realname >", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameGreaterThanOrEqualTo(String value) {
            addCriterion("realname >=", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLessThan(String value) {
            addCriterion("realname <", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLessThanOrEqualTo(String value) {
            addCriterion("realname <=", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLike(String value) {
            addCriterion("realname like", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotLike(String value) {
            addCriterion("realname not like", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameIn(List<String> values) {
            addCriterion("realname in", values, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotIn(List<String> values) {
            addCriterion("realname not in", values, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameBetween(String value1, String value2) {
            addCriterion("realname between", value1, value2, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotBetween(String value1, String value2) {
            addCriterion("realname not between", value1, value2, "realname");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andDesIsNull() {
            addCriterion("des is null");
            return (Criteria) this;
        }

        public Criteria andDesIsNotNull() {
            addCriterion("des is not null");
            return (Criteria) this;
        }

        public Criteria andDesEqualTo(String value) {
            addCriterion("des =", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotEqualTo(String value) {
            addCriterion("des <>", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesGreaterThan(String value) {
            addCriterion("des >", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesGreaterThanOrEqualTo(String value) {
            addCriterion("des >=", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesLessThan(String value) {
            addCriterion("des <", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesLessThanOrEqualTo(String value) {
            addCriterion("des <=", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesLike(String value) {
            addCriterion("des like", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotLike(String value) {
            addCriterion("des not like", value, "des");
            return (Criteria) this;
        }

        public Criteria andDesIn(List<String> values) {
            addCriterion("des in", values, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotIn(List<String> values) {
            addCriterion("des not in", values, "des");
            return (Criteria) this;
        }

        public Criteria andDesBetween(String value1, String value2) {
            addCriterion("des between", value1, value2, "des");
            return (Criteria) this;
        }

        public Criteria andDesNotBetween(String value1, String value2) {
            addCriterion("des not between", value1, value2, "des");
            return (Criteria) this;
        }

        public Criteria andIfvipIsNull() {
            addCriterion("ifvip is null");
            return (Criteria) this;
        }

        public Criteria andIfvipIsNotNull() {
            addCriterion("ifvip is not null");
            return (Criteria) this;
        }

        public Criteria andIfvipEqualTo(String value) {
            addCriterion("ifvip =", value, "ifvip");
            return (Criteria) this;
        }

        public Criteria andIfvipNotEqualTo(String value) {
            addCriterion("ifvip <>", value, "ifvip");
            return (Criteria) this;
        }

        public Criteria andIfvipGreaterThan(String value) {
            addCriterion("ifvip >", value, "ifvip");
            return (Criteria) this;
        }

        public Criteria andIfvipGreaterThanOrEqualTo(String value) {
            addCriterion("ifvip >=", value, "ifvip");
            return (Criteria) this;
        }

        public Criteria andIfvipLessThan(String value) {
            addCriterion("ifvip <", value, "ifvip");
            return (Criteria) this;
        }

        public Criteria andIfvipLessThanOrEqualTo(String value) {
            addCriterion("ifvip <=", value, "ifvip");
            return (Criteria) this;
        }

        public Criteria andIfvipLike(String value) {
            addCriterion("ifvip like", value, "ifvip");
            return (Criteria) this;
        }

        public Criteria andIfvipNotLike(String value) {
            addCriterion("ifvip not like", value, "ifvip");
            return (Criteria) this;
        }

        public Criteria andIfvipIn(List<String> values) {
            addCriterion("ifvip in", values, "ifvip");
            return (Criteria) this;
        }

        public Criteria andIfvipNotIn(List<String> values) {
            addCriterion("ifvip not in", values, "ifvip");
            return (Criteria) this;
        }

        public Criteria andIfvipBetween(String value1, String value2) {
            addCriterion("ifvip between", value1, value2, "ifvip");
            return (Criteria) this;
        }

        public Criteria andIfvipNotBetween(String value1, String value2) {
            addCriterion("ifvip not between", value1, value2, "ifvip");
            return (Criteria) this;
        }

        public Criteria andDes1IsNull() {
            addCriterion("des1 is null");
            return (Criteria) this;
        }

        public Criteria andDes1IsNotNull() {
            addCriterion("des1 is not null");
            return (Criteria) this;
        }

        public Criteria andDes1EqualTo(String value) {
            addCriterion("des1 =", value, "des1");
            return (Criteria) this;
        }

        public Criteria andDes1NotEqualTo(String value) {
            addCriterion("des1 <>", value, "des1");
            return (Criteria) this;
        }

        public Criteria andDes1GreaterThan(String value) {
            addCriterion("des1 >", value, "des1");
            return (Criteria) this;
        }

        public Criteria andDes1GreaterThanOrEqualTo(String value) {
            addCriterion("des1 >=", value, "des1");
            return (Criteria) this;
        }

        public Criteria andDes1LessThan(String value) {
            addCriterion("des1 <", value, "des1");
            return (Criteria) this;
        }

        public Criteria andDes1LessThanOrEqualTo(String value) {
            addCriterion("des1 <=", value, "des1");
            return (Criteria) this;
        }

        public Criteria andDes1Like(String value) {
            addCriterion("des1 like", value, "des1");
            return (Criteria) this;
        }

        public Criteria andDes1NotLike(String value) {
            addCriterion("des1 not like", value, "des1");
            return (Criteria) this;
        }

        public Criteria andDes1In(List<String> values) {
            addCriterion("des1 in", values, "des1");
            return (Criteria) this;
        }

        public Criteria andDes1NotIn(List<String> values) {
            addCriterion("des1 not in", values, "des1");
            return (Criteria) this;
        }

        public Criteria andDes1Between(String value1, String value2) {
            addCriterion("des1 between", value1, value2, "des1");
            return (Criteria) this;
        }

        public Criteria andDes1NotBetween(String value1, String value2) {
            addCriterion("des1 not between", value1, value2, "des1");
            return (Criteria) this;
        }

        public Criteria andDes2IsNull() {
            addCriterion("des2 is null");
            return (Criteria) this;
        }

        public Criteria andDes2IsNotNull() {
            addCriterion("des2 is not null");
            return (Criteria) this;
        }

        public Criteria andDes2EqualTo(String value) {
            addCriterion("des2 =", value, "des2");
            return (Criteria) this;
        }

        public Criteria andDes2NotEqualTo(String value) {
            addCriterion("des2 <>", value, "des2");
            return (Criteria) this;
        }

        public Criteria andDes2GreaterThan(String value) {
            addCriterion("des2 >", value, "des2");
            return (Criteria) this;
        }

        public Criteria andDes2GreaterThanOrEqualTo(String value) {
            addCriterion("des2 >=", value, "des2");
            return (Criteria) this;
        }

        public Criteria andDes2LessThan(String value) {
            addCriterion("des2 <", value, "des2");
            return (Criteria) this;
        }

        public Criteria andDes2LessThanOrEqualTo(String value) {
            addCriterion("des2 <=", value, "des2");
            return (Criteria) this;
        }

        public Criteria andDes2Like(String value) {
            addCriterion("des2 like", value, "des2");
            return (Criteria) this;
        }

        public Criteria andDes2NotLike(String value) {
            addCriterion("des2 not like", value, "des2");
            return (Criteria) this;
        }

        public Criteria andDes2In(List<String> values) {
            addCriterion("des2 in", values, "des2");
            return (Criteria) this;
        }

        public Criteria andDes2NotIn(List<String> values) {
            addCriterion("des2 not in", values, "des2");
            return (Criteria) this;
        }

        public Criteria andDes2Between(String value1, String value2) {
            addCriterion("des2 between", value1, value2, "des2");
            return (Criteria) this;
        }

        public Criteria andDes2NotBetween(String value1, String value2) {
            addCriterion("des2 not between", value1, value2, "des2");
            return (Criteria) this;
        }

        public Criteria andDes3IsNull() {
            addCriterion("des3 is null");
            return (Criteria) this;
        }

        public Criteria andDes3IsNotNull() {
            addCriterion("des3 is not null");
            return (Criteria) this;
        }

        public Criteria andDes3EqualTo(String value) {
            addCriterion("des3 =", value, "des3");
            return (Criteria) this;
        }

        public Criteria andDes3NotEqualTo(String value) {
            addCriterion("des3 <>", value, "des3");
            return (Criteria) this;
        }

        public Criteria andDes3GreaterThan(String value) {
            addCriterion("des3 >", value, "des3");
            return (Criteria) this;
        }

        public Criteria andDes3GreaterThanOrEqualTo(String value) {
            addCriterion("des3 >=", value, "des3");
            return (Criteria) this;
        }

        public Criteria andDes3LessThan(String value) {
            addCriterion("des3 <", value, "des3");
            return (Criteria) this;
        }

        public Criteria andDes3LessThanOrEqualTo(String value) {
            addCriterion("des3 <=", value, "des3");
            return (Criteria) this;
        }

        public Criteria andDes3Like(String value) {
            addCriterion("des3 like", value, "des3");
            return (Criteria) this;
        }

        public Criteria andDes3NotLike(String value) {
            addCriterion("des3 not like", value, "des3");
            return (Criteria) this;
        }

        public Criteria andDes3In(List<String> values) {
            addCriterion("des3 in", values, "des3");
            return (Criteria) this;
        }

        public Criteria andDes3NotIn(List<String> values) {
            addCriterion("des3 not in", values, "des3");
            return (Criteria) this;
        }

        public Criteria andDes3Between(String value1, String value2) {
            addCriterion("des3 between", value1, value2, "des3");
            return (Criteria) this;
        }

        public Criteria andDes3NotBetween(String value1, String value2) {
            addCriterion("des3 not between", value1, value2, "des3");
            return (Criteria) this;
        }

        public Criteria andDes4IsNull() {
            addCriterion("des4 is null");
            return (Criteria) this;
        }

        public Criteria andDes4IsNotNull() {
            addCriterion("des4 is not null");
            return (Criteria) this;
        }

        public Criteria andDes4EqualTo(String value) {
            addCriterion("des4 =", value, "des4");
            return (Criteria) this;
        }

        public Criteria andDes4NotEqualTo(String value) {
            addCriterion("des4 <>", value, "des4");
            return (Criteria) this;
        }

        public Criteria andDes4GreaterThan(String value) {
            addCriterion("des4 >", value, "des4");
            return (Criteria) this;
        }

        public Criteria andDes4GreaterThanOrEqualTo(String value) {
            addCriterion("des4 >=", value, "des4");
            return (Criteria) this;
        }

        public Criteria andDes4LessThan(String value) {
            addCriterion("des4 <", value, "des4");
            return (Criteria) this;
        }

        public Criteria andDes4LessThanOrEqualTo(String value) {
            addCriterion("des4 <=", value, "des4");
            return (Criteria) this;
        }

        public Criteria andDes4Like(String value) {
            addCriterion("des4 like", value, "des4");
            return (Criteria) this;
        }

        public Criteria andDes4NotLike(String value) {
            addCriterion("des4 not like", value, "des4");
            return (Criteria) this;
        }

        public Criteria andDes4In(List<String> values) {
            addCriterion("des4 in", values, "des4");
            return (Criteria) this;
        }

        public Criteria andDes4NotIn(List<String> values) {
            addCriterion("des4 not in", values, "des4");
            return (Criteria) this;
        }

        public Criteria andDes4Between(String value1, String value2) {
            addCriterion("des4 between", value1, value2, "des4");
            return (Criteria) this;
        }

        public Criteria andDes4NotBetween(String value1, String value2) {
            addCriterion("des4 not between", value1, value2, "des4");
            return (Criteria) this;
        }

        public Criteria andDes5IsNull() {
            addCriterion("des5 is null");
            return (Criteria) this;
        }

        public Criteria andDes5IsNotNull() {
            addCriterion("des5 is not null");
            return (Criteria) this;
        }

        public Criteria andDes5EqualTo(String value) {
            addCriterion("des5 =", value, "des5");
            return (Criteria) this;
        }

        public Criteria andDes5NotEqualTo(String value) {
            addCriterion("des5 <>", value, "des5");
            return (Criteria) this;
        }

        public Criteria andDes5GreaterThan(String value) {
            addCriterion("des5 >", value, "des5");
            return (Criteria) this;
        }

        public Criteria andDes5GreaterThanOrEqualTo(String value) {
            addCriterion("des5 >=", value, "des5");
            return (Criteria) this;
        }

        public Criteria andDes5LessThan(String value) {
            addCriterion("des5 <", value, "des5");
            return (Criteria) this;
        }

        public Criteria andDes5LessThanOrEqualTo(String value) {
            addCriterion("des5 <=", value, "des5");
            return (Criteria) this;
        }

        public Criteria andDes5Like(String value) {
            addCriterion("des5 like", value, "des5");
            return (Criteria) this;
        }

        public Criteria andDes5NotLike(String value) {
            addCriterion("des5 not like", value, "des5");
            return (Criteria) this;
        }

        public Criteria andDes5In(List<String> values) {
            addCriterion("des5 in", values, "des5");
            return (Criteria) this;
        }

        public Criteria andDes5NotIn(List<String> values) {
            addCriterion("des5 not in", values, "des5");
            return (Criteria) this;
        }

        public Criteria andDes5Between(String value1, String value2) {
            addCriterion("des5 between", value1, value2, "des5");
            return (Criteria) this;
        }

        public Criteria andDes5NotBetween(String value1, String value2) {
            addCriterion("des5 not between", value1, value2, "des5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table myuser
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table myuser
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}