package com.cx.codesigner.model;

public class MyUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.realname
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.des
     *
     * @mbggenerated
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.ifvip
     *
     * @mbggenerated
     */
    private String ifvip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.des1
     *
     * @mbggenerated
     */
    private String des1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.des2
     *
     * @mbggenerated
     */
    private String des2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.des3
     *
     * @mbggenerated
     */
    private String des3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.des4
     *
     * @mbggenerated
     */
    private String des4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.des5
     *
     * @mbggenerated
     */
    private String des5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.id
     *
     * @return the value of myuser.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.id
     *
     * @param id the value for myuser.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.name
     *
     * @return the value of myuser.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.name
     *
     * @param name the value for myuser.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.password
     *
     * @return the value of myuser.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.password
     *
     * @param password the value for myuser.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.phone
     *
     * @return the value of myuser.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.phone
     *
     * @param phone the value for myuser.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.email
     *
     * @return the value of myuser.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.email
     *
     * @param email the value for myuser.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.realname
     *
     * @return the value of myuser.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.realname
     *
     * @param realname the value for myuser.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.age
     *
     * @return the value of myuser.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.age
     *
     * @param age the value for myuser.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.sex
     *
     * @return the value of myuser.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.sex
     *
     * @param sex the value for myuser.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.des
     *
     * @return the value of myuser.des
     *
     * @mbggenerated
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.des
     *
     * @param des the value for myuser.des
     *
     * @mbggenerated
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.ifvip
     *
     * @return the value of myuser.ifvip
     *
     * @mbggenerated
     */
    public String getIfvip() {
        return ifvip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.ifvip
     *
     * @param ifvip the value for myuser.ifvip
     *
     * @mbggenerated
     */
    public void setIfvip(String ifvip) {
        this.ifvip = ifvip == null ? null : ifvip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.des1
     *
     * @return the value of myuser.des1
     *
     * @mbggenerated
     */
    public String getDes1() {
        return des1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.des1
     *
     * @param des1 the value for myuser.des1
     *
     * @mbggenerated
     */
    public void setDes1(String des1) {
        this.des1 = des1 == null ? null : des1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.des2
     *
     * @return the value of myuser.des2
     *
     * @mbggenerated
     */
    public String getDes2() {
        return des2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.des2
     *
     * @param des2 the value for myuser.des2
     *
     * @mbggenerated
     */
    public void setDes2(String des2) {
        this.des2 = des2 == null ? null : des2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.des3
     *
     * @return the value of myuser.des3
     *
     * @mbggenerated
     */
    public String getDes3() {
        return des3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.des3
     *
     * @param des3 the value for myuser.des3
     *
     * @mbggenerated
     */
    public void setDes3(String des3) {
        this.des3 = des3 == null ? null : des3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.des4
     *
     * @return the value of myuser.des4
     *
     * @mbggenerated
     */
    public String getDes4() {
        return des4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.des4
     *
     * @param des4 the value for myuser.des4
     *
     * @mbggenerated
     */
    public void setDes4(String des4) {
        this.des4 = des4 == null ? null : des4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.des5
     *
     * @return the value of myuser.des5
     *
     * @mbggenerated
     */
    public String getDes5() {
        return des5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.des5
     *
     * @param des5 the value for myuser.des5
     *
     * @mbggenerated
     */
    public void setDes5(String des5) {
        this.des5 = des5 == null ? null : des5.trim();
    }
}