package com.cx.codesigner.model;

import java.math.BigDecimal;
import java.util.List;

public class ResourceClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.classid
     *
     * @mbggenerated
     */
    private Integer classid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.subjectid
     *
     * @mbggenerated
     */
    private Integer subjectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.img
     *
     * @mbggenerated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.des2
     *
     * @mbggenerated
     */
    private String des2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.des3
     *
     * @mbggenerated
     */
    private String des3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.des4
     *
     * @mbggenerated
     */
    private String des4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.des1
     *
     * @mbggenerated
     */
    private byte[] des1;
    /**
     * 设置详细信息里面的图片列表
     * 展示截图信息
     * code/图片名称
     */
    private List<String> detailImageList;

    private String detailDescription;

    private String videourl;

    public String getVideourl() {
        return videourl;
    }

    public void setVideourl(String videourl) {
        this.videourl = videourl;
    }

    public String getDetailDescription() {
        return detailDescription;
    }

    public void setDetailDescription(String detailDescription) {
        this.detailDescription = detailDescription;
    }

    public List<String> getDetailImageList() {
        return detailImageList;
    }

    public void setDetailImageList(List<String> detailImageList) {
        this.detailImageList = detailImageList;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.code
     *
     * @return the value of resource.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.code
     *
     * @param code the value for resource.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.name
     *
     * @return the value of resource.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.name
     *
     * @param name the value for resource.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.classid
     *
     * @return the value of resource.classid
     *
     * @mbggenerated
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.classid
     *
     * @param classid the value for resource.classid
     *
     * @mbggenerated
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.subjectid
     *
     * @return the value of resource.subjectid
     *
     * @mbggenerated
     */
    public Integer getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.subjectid
     *
     * @param subjectid the value for resource.subjectid
     *
     * @mbggenerated
     */
    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.description
     *
     * @return the value of resource.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.description
     *
     * @param description the value for resource.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.url
     *
     * @return the value of resource.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.url
     *
     * @param url the value for resource.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.img
     *
     * @return the value of resource.img
     *
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.img
     *
     * @param img the value for resource.img
     *
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.price
     *
     * @return the value of resource.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.price
     *
     * @param price the value for resource.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.des2
     *
     * @return the value of resource.des2
     *
     * @mbggenerated
     */
    public String getDes2() {
        return des2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.des2
     *
     * @param des2 the value for resource.des2
     *
     * @mbggenerated
     */
    public void setDes2(String des2) {
        this.des2 = des2 == null ? null : des2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.des3
     *
     * @return the value of resource.des3
     *
     * @mbggenerated
     */
    public String getDes3() {
        return des3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.des3
     *
     * @param des3 the value for resource.des3
     *
     * @mbggenerated
     */
    public void setDes3(String des3) {
        this.des3 = des3 == null ? null : des3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.des4
     *
     * @return the value of resource.des4
     *
     * @mbggenerated
     */
    public String getDes4() {
        return des4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.des4
     *
     * @param des4 the value for resource.des4
     *
     * @mbggenerated
     */
    public void setDes4(String des4) {
        this.des4 = des4 == null ? null : des4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.des1
     *
     * @return the value of resource.des1
     *
     * @mbggenerated
     */
    public byte[] getDes1() {
        return des1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.des1
     *
     * @param des1 the value for resource.des1
     *
     * @mbggenerated
     */
    public void setDes1(byte[] des1) {
        this.des1 = des1;
    }
}