package com.cx.codesigner.model;

import java.util.List;

public class Subject {
    private List<ClassType> classTypeList;
    private  List<ResourceClass> leftResource;
    private List<ResourceClass> centerResource;
    private List<ResourceClass> rightResource;

    public List<ClassType> getClassTypeList() {
        return classTypeList;
    }

    public void setClassTypeList(List<ClassType> classTypeList) {
        this.classTypeList = classTypeList;
    }

    public List<ResourceClass> getLeftResource() {
        return leftResource;
    }

    public void setLeftResource(List<ResourceClass> leftResource) {
        this.leftResource = leftResource;
    }

    public List<ResourceClass> getCenterResource() {
        return centerResource;
    }

    public void setCenterResource(List<ResourceClass> centerResource) {
        this.centerResource = centerResource;
    }

    public List<ResourceClass> getRightResource() {
        return rightResource;
    }

    public void setRightResource(List<ResourceClass> rightResource) {
        this.rightResource = rightResource;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.subjectcode
     *
     * @mbggenerated
     */
    private String subjectcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.subjectname
     *
     * @mbggenerated
     */
    private String subjectname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.id
     *
     * @return the value of subject.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.id
     *
     * @param id the value for subject.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.subjectcode
     *
     * @return the value of subject.subjectcode
     *
     * @mbggenerated
     */
    public String getSubjectcode() {
        return subjectcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.subjectcode
     *
     * @param subjectcode the value for subject.subjectcode
     *
     * @mbggenerated
     */
    public void setSubjectcode(String subjectcode) {
        this.subjectcode = subjectcode == null ? null : subjectcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.subjectname
     *
     * @return the value of subject.subjectname
     *
     * @mbggenerated
     */
    public String getSubjectname() {
        return subjectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.subjectname
     *
     * @param subjectname the value for subject.subjectname
     *
     * @mbggenerated
     */
    public void setSubjectname(String subjectname) {
        this.subjectname = subjectname == null ? null : subjectname.trim();
    }
}